import { useNavigate, useLocation } from 'react-router-dom';
import { useLanguage } from '../../context/LanguageContext';
import { DEMO_CASES, RISK_MAP } from '../../data/mockData';
import { ArrowLeft, Download, Printer, Shield, Eye } from 'lucide-react';

export default function ReportPage() {
  const { t } = useLanguage();
  const navigate = useNavigate();
  const location = useLocation();
  const screening = location.state?.screening || DEMO_CASES[1];
  const prediction = screening?.prediction || DEMO_CASES[1].prediction;
  const predClass = prediction?.class ?? 2;
  const risk = RISK_MAP[predClass] || RISK_MAP[2];

  const handleDownloadPDF = () => {
    // For the prototype, generate a simple text-based PDF using jspdf
    import('jspdf').then(({ jsPDF }) => {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();

      // Header
      doc.setFillColor(10, 22, 40);
      doc.rect(0, 0, pageWidth, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont(undefined, 'bold');
      doc.text('NetraAI', pageWidth / 2, 18, { align: 'center' });
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text('AI-Assisted Retinal Screening Report', pageWidth / 2, 28, { align: 'center' });

      let y = 55;
      doc.setTextColor(0, 0, 0);

      // Patient Information
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text('Patient Information', 20, y);
      y += 10;
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');

      const patientInfo = [
        ['Patient ID', screening.patientId],
        ['Name', screening.patientName || 'N/A'],
        ['Age', `${screening.age || 'N/A'}`],
        ['Gender', screening.gender || 'N/A'],
        ['Location', screening.village || 'N/A'],
        ['Date', screening.date || new Date().toISOString().split('T')[0]],
      ];

      patientInfo.forEach(([label, value]) => {
        doc.setFont(undefined, 'bold');
        doc.text(`${label}:`, 20, y);
        doc.setFont(undefined, 'normal');
        doc.text(value, 70, y);
        y += 7;
      });

      y += 10;

      // Screening Result
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text('AI Screening Result', 20, y);
      y += 10;
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');

      doc.setFont(undefined, 'bold');
      doc.text('Prediction:', 20, y);
      doc.setFont(undefined, 'normal');
      doc.text(prediction.label, 70, y);
      y += 7;

      doc.setFont(undefined, 'bold');
      doc.text('Confidence:', 20, y);
      doc.setFont(undefined, 'normal');
      doc.text(`${Math.round(prediction.confidence * 100)}%`, 70, y);
      y += 7;

      doc.setFont(undefined, 'bold');
      doc.text('Risk Level:', 20, y);
      doc.setFont(undefined, 'normal');
      doc.text(risk.label, 70, y);
      y += 15;

      // Probability Distribution
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text('DR Classification Probabilities', 20, y);
      y += 10;
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');

      const probs = [
        ['No DR', prediction.probabilities.no_dr],
        ['Mild DR', prediction.probabilities.mild],
        ['Moderate DR', prediction.probabilities.moderate],
        ['Severe DR', prediction.probabilities.severe],
        ['Proliferative DR', prediction.probabilities.proliferative],
      ];

      probs.forEach(([label, value]) => {
        doc.text(`${label}:`, 20, y);
        doc.text(`${Math.round(value * 100)}%`, 70, y);

        // Draw bar
        doc.setFillColor(200, 200, 200);
        doc.rect(90, y - 3, 80, 4, 'F');
        doc.setFillColor(13, 148, 136);
        doc.rect(90, y - 3, 80 * value, 4, 'F');

        y += 8;
      });

      y += 10;

      // Disclaimer
      doc.setFillColor(248, 250, 252);
      doc.rect(15, y - 5, pageWidth - 30, 35, 'F');
      doc.setFontSize(9);
      doc.setFont(undefined, 'bold');
      doc.text('Important Notice', 20, y + 2);
      doc.setFont(undefined, 'normal');
      doc.setFontSize(8);
      const disclaimer = 'This AI-assisted screening result is not a final medical diagnosis. Final clinical assessment must be performed by a qualified healthcare professional. This system is intended for screening and clinical decision support only.';
      const splitDisclaimer = doc.splitTextToSize(disclaimer, pageWidth - 45);
      doc.text(splitDisclaimer, 20, y + 10);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by NetraAI on ${new Date().toLocaleString()}`, pageWidth / 2, 285, { align: 'center' });

      doc.save(`NetraAI_Report_${screening.patientId}_${screening.date || 'report'}.pdf`);
    });
  };

  return (
    <div style={{ maxWidth: 720, margin: '0 auto' }}>
      <button className="btn btn-ghost" onClick={() => navigate(-1)} style={{ marginBottom: 'var(--space-4)' }}>
        <ArrowLeft size={16} /> {t('back')}
      </button>

      {/* Report Preview */}
      <div className="card" style={{ marginBottom: 'var(--space-6)' }}>
        {/* Report Header */}
        <div style={{ background: 'var(--navy-900)', color: 'var(--white)', padding: 'var(--space-8)', textAlign: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 'var(--space-2)', marginBottom: 'var(--space-2)' }}>
            <Eye size={24} color="var(--teal-400)" />
            <span style={{ fontSize: 'var(--font-xl)', fontWeight: 700 }}>Netra<span style={{ color: 'var(--teal-400)' }}>AI</span></span>
          </div>
          <p style={{ fontSize: 'var(--font-sm)', color: 'var(--gray-400)' }}>{t('screeningReport')}</p>
        </div>

        <div className="card-body">
          {/* Patient Information */}
          <div className="result-section">
            <h3>{t('patientInformation')}</h3>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--space-3)' }}>
              {[
                [t('patientId'), screening.patientId],
                [t('patientName'), screening.patientName || 'N/A'],
                [t('age'), screening.age || 'N/A'],
                [t('gender'), screening.gender || 'N/A'],
                [t('village'), screening.village || 'N/A'],
                [t('date'), screening.date || new Date().toISOString().split('T')[0]],
                [t('diabetesDuration'), screening.diabetesDuration ? `${screening.diabetesDuration} years` : 'N/A'],
              ].map(([label, value], i) => (
                <div key={i} style={{ padding: 'var(--space-2) 0', borderBottom: '1px solid var(--gray-100)' }}>
                  <div style={{ fontSize: 'var(--font-xs)', color: 'var(--gray-500)', fontWeight: 600 }}>{label}</div>
                  <div style={{ fontSize: 'var(--font-sm)', color: 'var(--navy-900)', fontWeight: 500, marginTop: 2 }}>{value}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Screening Result */}
          <div className="result-section">
            <h3>{t('screeningResult')}</h3>
            <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-4)', padding: 'var(--space-4)', background: 'var(--gray-50)', borderRadius: 'var(--radius-md)' }}>
              <div>
                <div style={{ fontSize: 'var(--font-xs)', color: 'var(--gray-500)', fontWeight: 600, textTransform: 'uppercase' }}>AI Prediction</div>
                <div style={{ fontSize: 'var(--font-xl)', fontWeight: 700, color: risk.color }}>{prediction.label}</div>
              </div>
              <div style={{ marginLeft: 'auto', textAlign: 'right' }}>
                <div style={{ fontSize: 'var(--font-xs)', color: 'var(--gray-500)', fontWeight: 600 }}>{t('modelConfidence')}</div>
                <div style={{ fontSize: 'var(--font-xl)', fontWeight: 700, color: 'var(--navy-900)' }}>{Math.round(prediction.confidence * 100)}%</div>
              </div>
            </div>
          </div>

          {/* Risk */}
          <div className="result-section">
            <h3>{t('referralRecommendation')}</h3>
            <div className={`referral-card ${risk.level === 'low' ? 'low' : risk.level === 'moderate' ? 'moderate' : 'high'}`}>
              <div>
                <h4>{risk.label}</h4>
                <p style={{ fontSize: 'var(--font-sm)' }}>
                  {prediction.class === 0 ? t('noRiskText') :
                   prediction.class === 1 ? t('mildRiskText') :
                   prediction.class === 2 ? t('moderateRiskText') : t('severeRiskText')}
                </p>
              </div>
            </div>
          </div>

          {/* Disclaimer */}
          <div style={{
            background: 'var(--gray-50)', border: '1px solid var(--gray-200)',
            borderRadius: 'var(--radius-md)', padding: 'var(--space-5)', marginTop: 'var(--space-6)'
          }}>
            <h4 style={{ fontSize: 'var(--font-sm)', fontWeight: 700, marginBottom: 'var(--space-2)', display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
              <Shield size={14} /> {t('importantNotice')}
            </h4>
            <p style={{ fontSize: 'var(--font-xs)', color: 'var(--gray-600)', lineHeight: 1.7 }}>
              {t('disclaimerText')}
            </p>
          </div>

          {/* Screening Centre */}
          <div style={{ marginTop: 'var(--space-6)', padding: 'var(--space-4) 0', borderTop: '1px solid var(--gray-200)' }}>
            <div style={{ fontSize: 'var(--font-xs)', color: 'var(--gray-500)' }}>{t('screeningCentre')}</div>
            <div style={{ fontSize: 'var(--font-sm)', fontWeight: 500, marginTop: 2 }}>PHC Bharatpur, Rajasthan</div>
          </div>
        </div>
      </div>

      {/* Download Actions */}
      <div style={{ display: 'flex', gap: 'var(--space-3)', justifyContent: 'center' }}>
        <button className="btn btn-primary btn-lg" onClick={handleDownloadPDF}>
          <Download size={18} /> {t('downloadPdf')}
        </button>
        <button className="btn btn-secondary btn-lg" onClick={() => window.print()}>
          <Printer size={18} /> Print
        </button>
      </div>

      <div className="disclaimer" style={{ marginTop: 'var(--space-6)' }}>
        <Shield size={14} /> {t('screeningDisclaimer')}
      </div>
    </div>
  );
}
